# postgres, mongo, redis, kafka
version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: gigmatch-postgres
    environment:
      POSTGRES_DB: gigmatch
      POSTGRES_USER: gigmatch
      POSTGRES_PASSWORD: gigmatch
    ports:
      - "5432:5432"

  mongo:
    image: mongo:8
    container_name: gigmatch-mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: gigmatch-redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    container_name: gigmatch-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: gigmatch-zookeeper
    ports:
      - "2181:2181"
